"""ZeroSlip backtest_sniper_strategy.py: edit settings below, then run python3 backtest_sniper_strategy.py.

Python 3.11+. Install the packages listed below once in your Python environment.
Alternatively, uv run backtest_sniper_strategy.py handles them automatically. No config files or flags.
Generated by tools/build_standalone.py from scripts/; edit strategy logic there.
"""
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "aiohttp>=3.12,<4",
#   "websockets>=15,<16",
#   "cachetools>=5.5,<8",
#   "orjson>=3.10,<4",
#   "zstandard>=0.23,<1",
# ]
# ///

# SETTINGS — edit this section. Backtesting never submits orders.
REPLAY_FILE = ''  # Optional path to a downloaded .jsonl or .jsonl.zst archive.
CONFIG = {
    'backtest': {
        'hours': 1,  # Completed UTC hours; ignored when REPLAY_FILE is set.
        'allow_gaps': False,
        'buy_latency_ms': 400,
        'sell_latency_ms': 400,
        'service_fee': 0.0025,
        'extra_fee': 0.0005,
    },
    'sniper': {'min_initial_buy': 20.0, 'take_profit': 50.0, 'stop_loss': 20.0, 'idle_seconds': 300.0},
    'trade': {'buy_amount': 0.001, 'buy_slippage': 20.0, 'sell_slippage': 99.0},
}

# IMPLEMENTATION — the same runtime and strategy as scripts/, bundled into this file.
from types import SimpleNamespace
import asyncio
import copy
import logging
import math
from pathlib import Path
from urllib.parse import urlparse
import aiohttp
import orjson
from collections import Counter
from datetime import datetime, timedelta, timezone
import io
import tempfile
import zstandard


BASE58_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'


WSOL = 'So11111111111111111111111111111111111111112'


USDC = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'


SOL_USDC_POOL = 'Gf7sXMoP8iRw4iiXmJ1nq4vxcRycbGXy5RL8a8LnTd3v'


DEFAULTS = {
    'network': {
        'trade_url': 'https://api.zeroslip.ai',
        'stream_url': 'wss://stream.zeroslip.ai/',
        'replay_url': 'https://replay.pumpapi.io',
        'rpc_url': 'https://api.mainnet-beta.solana.com',
    },
    'trade': {
        'buy_amount': 0.001,
        'buy_slippage': 20.0,
        'sell_slippage': 99.0,
        'priority_fee': 0.0001,
        'confirmation_seconds': 3.0,
    },
    'wallet': {'public_key': ''},
    'copytrader': {'wallets': [], 'token_mints': [], 'buy_fraction': 0.1, 'max_buy_amount': 0.01},
    'sniper': {
        'token_mint': '',
        'min_initial_buy': 20.0,
        'take_profit': 50.0,
        'stop_loss': 20.0,
        'idle_seconds': 300.0,
    },
    'backtest': {
        'hours': 10,
        'allow_gaps': False,
        'buy_latency_ms': 400,
        'sell_latency_ms': 400,
        'service_fee': 0.0025,
        'extra_fee': 0.0005,
    },
    'sell': {'token_mints': [], 'slippage': 100.0},
}


class ConfigError(ValueError):
    pass


class StopBot(RuntimeError):
    """Execution is rejected or uncertain: stop without sending another order."""


def address(value, label):
    if not isinstance(value, str) or not 32 <= len(value) <= 44 or any(c not in BASE58_ALPHABET for c in value):
        raise ConfigError(f'{label} must be a Solana base58 address')
    # Verify decoded length, not just the alphabet.
    number = 0
    for char in value:
        number = number * 58 + BASE58_ALPHABET.index(char)
    size = (number.bit_length() + 7) // 8 + len(value) - len(value.lstrip('1'))
    if size != 32:
        raise ConfigError(f'{label} must decode to 32 bytes')
    return value


def validate_config(overrides):
    """Merge and validate settings from either TOML or a single-file Python dict."""
    cfg = copy.deepcopy(DEFAULTS)
    if not isinstance(overrides, dict):
        raise ConfigError('Settings must be a dictionary of configuration sections')
    for section, values in overrides.items():
        if section not in cfg or not isinstance(values, dict):
            raise ConfigError(f'Unknown or invalid configuration section: {section}')
        for key, value in values.items():
            if section == 'trade' and key == 'quote_mint':
                logging.getLogger(__name__).warning(
                    'Ignoring deprecated trade.quote_mint; SOL/USDC quotes come from each event. '
                    'Remove this key from your config'
                )
                continue
            if key not in cfg[section]:
                raise ConfigError(f'Unknown configuration option: {section}.{key}')
            default = cfg[section][key]
            if isinstance(default, bool):
                valid = isinstance(value, bool)
            elif isinstance(default, (float, int)):
                valid = isinstance(value, (float, int)) and not isinstance(value, bool) and math.isfinite(value)
            else:
                valid = isinstance(value, type(default))
            if not valid:
                raise ConfigError(f'Invalid value type: {section}.{key}')
            cfg[section][key] = value
    for section, key in [
        ('trade', 'buy_amount'),
        ('trade', 'confirmation_seconds'),
        ('copytrader', 'max_buy_amount'),
        ('sniper', 'idle_seconds'),
        ('sniper', 'take_profit'),
        ('sniper', 'stop_loss'),
    ]:
        if cfg[section][key] <= 0:
            raise ConfigError(f'{section}.{key} must be positive')
    for section, key in [('backtest', 'hours')]:
        if not isinstance(cfg[section][key], int) or cfg[section][key] < 1:
            raise ConfigError(f'{section}.{key} must be a positive integer')
    for key in ('buy_slippage', 'sell_slippage'):
        if not 0 <= cfg['trade'][key] < 100:
            raise ConfigError(f'trade.{key} must be between 0 and 100 (exclusive)')
    if not 0 <= cfg['sell']['slippage'] <= 100:
        raise ConfigError('sell.slippage must be between 0 and 100 (inclusive)')
    if not 0 < cfg['copytrader']['buy_fraction'] <= 1:
        raise ConfigError('copytrader.buy_fraction must be between 0 and 1')
    if not 0 < cfg['sniper']['stop_loss'] < 100:
        raise ConfigError('sniper.stop_loss must be between 0 and 100 (exclusive)')
    for section, key in [
        ('trade', 'priority_fee'),
        ('sniper', 'min_initial_buy'),
        ('backtest', 'buy_latency_ms'),
        ('backtest', 'sell_latency_ms'),
        ('backtest', 'service_fee'),
        ('backtest', 'extra_fee'),
    ]:
        if cfg[section][key] < 0:
            raise ConfigError(f'{section}.{key} cannot be negative')
    if cfg['backtest']['service_fee'] + cfg['backtest']['extra_fee'] >= 1:
        raise ConfigError('Backtest fee fractions must total less than 1')
    for key, url in cfg['network'].items():
        parsed = urlparse(url)
        if (
            parsed.scheme != ('wss' if key == 'stream_url' else 'https')
            or not parsed.hostname
            or parsed.username
            or parsed.password
            or parsed.query
        ):
            raise ConfigError(f'network.{key} must be a secure URL without credentials or query parameters')
    for section, key in [('copytrader', 'wallets'), ('copytrader', 'token_mints'), ('sell', 'token_mints')]:
        for item in cfg[section][key]:
            address(item, f'{section}.{key}')
    if cfg['sniper']['token_mint']:
        address(cfg['sniper']['token_mint'], 'sniper.token_mint')
    return cfg


def validate_setup(cfg, args, kind):
    if cfg['wallet']['public_key']:
        address(cfg['wallet']['public_key'], 'wallet.public_key')
    if kind == 'copytrader' and not cfg['copytrader']['wallets']:
        raise ConfigError('Set copytrader.wallets to the public wallets you want to follow')
    if kind == 'copytrader' and cfg['wallet']['public_key'] in cfg['copytrader']['wallets']:
        raise ConfigError('Do not copy your own trading wallet')
    if kind == 'sell':
        if not args.live and not cfg['wallet']['public_key']:
            raise ConfigError('Sell preview needs wallet.public_key (or --wallet in CLI scripts)')
        if args.all and (args.mint or cfg['sell']['token_mints']):
            raise ConfigError('Choose all balances or specific token mints, not both')
        if not args.all and not cfg['sell']['token_mints']:
            raise ConfigError('Set sell.token_mints or select all balances')
    if getattr(args, 'live', False):
        credentials()


def positive(value):
    try:
        value = float(value)
        return value if math.isfinite(value) and value > 0 else 0.0
    except (ValueError, TypeError):
        return 0.0


class QuoteSizing:
    """Original two-quote strategy: SOL sizes, converted to USDC at stream price."""

    def __init__(self):
        self.sol_price = 80.0  # Original fallback until the trusted pool updates.

    def observe(self, event):
        if event.get('poolId') != SOL_USDC_POOL:
            return False
        price = positive(event.get('price'))
        if price:
            self.sol_price = 1 / price
        return True

    def amount(self, quote, sol_amount):
        return sol_amount if quote == WSOL else sol_amount * self.sol_price

    @staticmethod
    def supports(quote):
        return quote in (WSOL, USDC)


def run(main):
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logging.info('Stopped. Existing live positions remain in the wallet.')
    except (StopBot, ConfigError) as exc:
        logging.error('%s', exc)
        raise SystemExit(1) from exc
    except Exception as exc:
        logging.exception('Unexpected runtime failure (%s); stopped', type(exc).__name__)
        raise SystemExit(1) from exc


class Backtest:
    """Upstream replay ordering, fills, fees and SOL-equivalent accounting."""

    def __init__(self, cfg):
        self.cfg = cfg
        self.quotes = QuoteSizing()
        self.positions = {}
        self.trades = []
        self.last_ts = 0
        self.first_ts = self.window_end = None
        self.seen = self.skipped = self.missed = self.buys = self.creates = 0

    def fill_buy(self, mint, pos):
        decision, fill = pos['decision_price'], pos['cur_price']
        ceiling = decision / (1 - min(self.cfg['trade']['buy_slippage'], 99.9) / 100)
        if fill > ceiling:
            self.missed += 1
            self.positions.pop(mint, None)
            return
        amount, quote = pos['amount'], pos['quote_mint']
        pos.update(
            state='held',
            entry_price=fill,
            quote_spent=amount,
            tokens=amount
            * (1 - self.cfg['backtest']['service_fee'] - self.cfg['backtest']['extra_fee'] - pos['entry_pool_fee'])
            / fill,
            sol_price=self.quotes.sol_price,
            spent_sol=amount if quote == WSOL else amount / self.quotes.sol_price,
            buy_slip=(fill / decision - 1) * 100,
            last_ts=pos['buy_fill_ts'],
        )
        self.buys += 1

    def trigger_sell(self, pos, ts, reason):
        pos.update(state='pending_sell', sell_reason=reason, sell_fill_ts=ts + self.cfg['backtest']['sell_latency_ms'])

    def close(self, mint, pos, exit_price, reason):
        gross = pos['tokens'] * exit_price
        fee = self.cfg['backtest']['service_fee'] + self.cfg['backtest']['extra_fee']
        proceeds = gross * (1 - (fee + pos['last_pool_fee']))
        pnl = proceeds - pos['quote_spent']
        fee_quote = pos['quote_spent'] * (fee + pos['entry_pool_fee']) + gross * (fee + pos['last_pool_fee'])
        is_sol = pos['quote_mint'] == WSOL
        self.trades.append(
            {
                'mint': mint,
                'quote_mint': pos['quote_mint'],
                'reason': reason,
                'pct': (exit_price - pos['entry_price']) / pos['entry_price'] * 100,
                'pnl': pnl,
                'pnl_sol': pnl if is_sol else pnl / pos['sol_price'],
                'spent_sol': pos['spent_sol'],
                'fee_sol': fee_quote if is_sol else fee_quote / pos['sol_price'],
                'buy_slip': pos['buy_slip'],
            }
        )
        self.positions.pop(mint, None)

    def resolve(self, ts):
        for mint, pos in list(self.positions.items()):
            if pos['state'] == 'pending_buy' and pos['buy_fill_ts'] <= ts:
                self.fill_buy(mint, pos)
            elif pos['state'] == 'pending_sell' and pos['sell_fill_ts'] <= ts:
                self.close(mint, pos, pos['cur_price'], pos['sell_reason'])
            elif pos['state'] == 'held' and ts - pos['last_ts'] > self.cfg['sniper']['idle_seconds'] * 1000:
                self.trigger_sell(pos, pos['last_ts'] + self.cfg['sniper']['idle_seconds'] * 1000, 'idle')

    def handle_event(self, event):
        self.seen += 1
        ts = event['timestamp']
        self.last_ts = ts
        self.first_ts = ts if self.first_ts is None else min(self.first_ts, ts)
        self.window_end = ts if self.window_end is None else max(self.window_end, ts)
        # Preserve upstream ordering: resolve BEFORE applying this event's price,
        # including timestamps that arrive out of order in the archive.
        self.resolve(ts)
        if event['action'] not in ('buy', 'sell', 'add', 'remove', 'create', 'migrate', 'createPool'):
            return
        mint = event['mint']
        if self.quotes.observe(event):
            return
        if event['action'] == 'create' and event['pool'] == 'pump' and not event.get('mayhemMode'):
            self.creates += 1
            quote = event['quoteMint']
            threshold = self.quotes.amount(quote, self.cfg['sniper']['min_initial_buy'])
            if self.quotes.supports(quote) and event['quoteAmount'] > threshold and mint not in self.positions:
                pool_fee = event['poolFeeRate']
                self.positions[mint] = {
                    'state': 'pending_buy',
                    'quote_mint': quote,
                    'amount': self.quotes.amount(quote, self.cfg['trade']['buy_amount']),
                    'decision_price': event['price'],
                    'cur_price': event['price'],
                    'entry_pool_fee': pool_fee,
                    'last_pool_fee': pool_fee,
                    'buy_fill_ts': ts + self.cfg['backtest']['buy_latency_ms'],
                    'buy_slip': 0.0,
                }
        elif mint in self.positions:
            pos = self.positions[mint]
            if event['action'] in ('buy', 'sell', 'add', 'remove', 'migrate') and (
                event['pool'] == 'pump' or (event['pool'] == 'pump-amm' and event.get('poolCreatedBy') == 'pump')
            ):
                price = event['price']
                pos.update(cur_price=price, last_pool_fee=event['poolFeeRate'])
                if pos['state'] == 'held':
                    change = (price - pos['entry_price']) / pos['entry_price'] * 100
                    if change > self.cfg['sniper']['take_profit'] or change < -self.cfg['sniper']['stop_loss']:
                        self.trigger_sell(pos, ts, 'tp' if change > self.cfg['sniper']['take_profit'] else 'sl')
            if pos['state'] == 'held':
                pos['last_ts'] = ts

    def finish(self):
        # Upstream forces in-flight buys to fill, then closes at last-known price.
        for mint, pos in list(self.positions.items()):
            if pos['state'] == 'pending_buy':
                self.fill_buy(mint, pos)
        for mint, pos in list(self.positions.items()):
            reason = (
                pos['sell_reason']
                if pos['state'] == 'pending_sell'
                else ('idle' if self.last_ts - pos['last_ts'] > self.cfg['sniper']['idle_seconds'] * 1000 else 'end')
            )
            self.close(mint, pos, pos['cur_price'], reason)
        pnl_sol = sum(trade['pnl_sol'] for trade in self.trades)
        volume = sum(trade['spent_sol'] for trade in self.trades)
        wins = sum(trade['pnl_sol'] > 0 for trade in self.trades)
        logging.info(
            'Events=%s creates=%s buys=%s skipped=%s closed=%s missed=%s',
            self.seen,
            self.creates,
            self.buys,
            self.skipped,
            len(self.trades),
            self.missed,
        )
        logging.info(
            'Modeled PnL=%+.8f SOL-equivalent; WSOL=%+.8f; USDC=%+.8f; wins=%s/%s',
            pnl_sol,
            sum(t['pnl'] for t in self.trades if t['quote_mint'] == WSOL),
            sum(t['pnl'] for t in self.trades if t['quote_mint'] == USDC),
            wins,
            len(self.trades),
        )
        logging.info(
            'Volume=%s SOL-equivalent; ROI=%+.2f%%; fees=%s SOL-equivalent',
            volume,
            pnl_sol / volume * 100 if volume else 0,
            sum(t['fee_sol'] for t in self.trades),
        )
        count = len(self.trades)
        if not count:
            logging.info('No trades filled in this window; check missed entries and your entry/slippage settings.')
        reasons = Counter(t['reason'] for t in self.trades)
        logging.info(
            'Exits: tp=%s sl=%s idle=%s end=%s; win_rate=%.2f%%',
            reasons['tp'],
            reasons['sl'],
            reasons['idle'],
            reasons['end'],
            wins / count * 100 if count else 0,
        )
        logging.info(
            'Average move=%+.2f%%; average entry slippage=%+.2f%%',
            sum(t['pct'] for t in self.trades) / count if count else 0,
            sum(t['buy_slip'] for t in self.trades) / count if count else 0,
        )
        if self.trades:
            for label, trade in [
                ('Best', max(self.trades, key=lambda t: t['pnl_sol'])),
                ('Worst', min(self.trades, key=lambda t: t['pnl_sol'])),
            ]:
                logging.info(
                    '%s trade: mint=%s pnl=%+.8f SOL-equivalent move=%+.2f%% reason=%s',
                    label,
                    trade['mint'],
                    trade['pnl_sol'],
                    trade['pct'],
                    trade['reason'],
                )
        if self.first_ts is not None:
            start = datetime.fromtimestamp(self.first_ts / 1000, timezone.utc)
            end = datetime.fromtimestamp(self.window_end / 1000, timezone.utc)
            logging.info('Replay window: %s to %s UTC', start.isoformat(), end.isoformat())
        logging.info(
            'Original replay model: last-known-price fills, end-window forced fills; not live execution guarantees.'
        )


def replay_file(path, strategy, compressed=None):
    path = Path(path)
    if compressed is None:
        compressed = path.suffix == '.zst'
    with path.open('rb') as file:
        if compressed:
            with zstandard.ZstdDecompressor().stream_reader(file) as reader:
                read_lines(io.BufferedReader(reader), strategy)
        else:
            read_lines(file, strategy)


def read_lines(reader, strategy):
    for line in reader:
        if not line.strip():
            continue
        try:
            event = orjson.loads(line)
        except orjson.JSONDecodeError:
            strategy.skipped += 1
            continue
        if not isinstance(event, dict):
            strategy.skipped += 1
            continue
        try:
            # Validate only inputs that can poison time or create/update positions.
            ts = event.get('timestamp')
            if not finite(ts) or ts < 0:
                raise ValueError('Invalid timestamp')
            launch = (
                event.get('action') == 'create'
                and event.get('pool') == 'pump'
                and not event.get('mayhemMode')
                and strategy.quotes.supports(event.get('quoteMint'))
            )
            amount = event.get('quoteAmount')
            entry = (
                launch
                and finite(amount)
                and amount > strategy.quotes.amount(event['quoteMint'], strategy.cfg['sniper']['min_initial_buy'])
            )
            update = (
                event.get('mint') in strategy.positions
                and event.get('action') in ('buy', 'sell', 'add', 'remove', 'migrate')
                and (
                    event.get('pool') == 'pump'
                    or (event.get('pool') == 'pump-amm' and event.get('poolCreatedBy') == 'pump')
                )
            )
            if entry or update:
                price, fee = event.get('price'), event.get('poolFeeRate')
                if not finite(price) or price <= 0 or not finite(fee) or not 0 <= fee < 1:
                    raise ValueError('Invalid price or pool fee')
            strategy.handle_event(event)
        except (KeyError, TypeError, ValueError, ZeroDivisionError):
            strategy.skipped += 1


def finite(value):
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value)


STORAGE_ERROR = (
    'Cannot write archive to temporary storage. Free space, set TMPDIR to a writable folder with space, or use --file'
)


class ArchiveFile:
    """Translate only file I/O errors; preserve a failing download during close."""

    def __init__(self, destination):
        self.destination = destination

    @staticmethod
    def storage_call(method, *args):
        try:
            return method(*args)
        except OSError as exc:
            raise StopBot(STORAGE_ERROR) from exc

    def __enter__(self):
        self.file = self.storage_call(Path(self.destination).open, 'wb')
        return self

    def write(self, chunk):
        self.storage_call(self.file.write, chunk)

    def __exit__(self, error_type, error, traceback):
        try:
            self.storage_call(self.file.close)
        except StopBot:
            if error_type is None:
                raise
            logging.warning('Archive close also failed; preserving the original error')


async def download_hour(session, cfg, hour, destination):
    url = f'{cfg["network"]["replay_url"].rstrip("/")}/{hour:%Y/%m/%d/%H}.jsonl.zst'
    logging.info('Downloading archive %s UTC', hour.strftime('%Y-%m-%d %H:00'))
    try:
        async with session.get(url) as response:
            if response.status == 404 and cfg['backtest']['allow_gaps']:
                logging.warning('Skipping missing archive hour')
                return False
            if response.status != 200:
                hint = (
                    ('; the newest completed hour may still be uploading. Wait 90 seconds and retry, or use --file')
                    if response.status == 404
                    else '; use --file'
                )
                raise StopBot(f'Archive download returned HTTP {response.status}{hint}')
            with ArchiveFile(destination) as file:
                async for chunk in response.content.iter_chunked(1 << 20):
                    file.write(chunk)
    except (aiohttp.ClientError, asyncio.TimeoutError, OSError) as exc:
        raise StopBot(f'Archive network failure: {type(exc).__name__}: {exc}; retry or use --file') from exc
    return True


async def main():
    cfg, args = setup('backtest')
    strategy = Backtest(cfg)
    if args.file:
        replay_file(args.file, strategy)
    else:
        now = datetime.now(timezone.utc).replace(minute=0, second=0, microsecond=0)
        async with aiohttp.ClientSession(
            timeout=aiohttp.ClientTimeout(total=None, sock_connect=30, sock_read=120)
        ) as session:
            with tempfile.TemporaryDirectory(prefix='zeroslip-replay-') as folder:
                path = Path(folder) / 'hour.jsonl.zst'
                for offset in range(cfg['backtest']['hours'], 0, -1):
                    if await download_hour(session, cfg, now - timedelta(hours=offset), path):
                        await asyncio.to_thread(replay_file, path, strategy, True)
    strategy.finish()


def credentials():
    raise ConfigError('Backtesting never submits orders')


def setup(kind):
    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
    if not isinstance(False, bool) or not isinstance(False, bool):
        raise ConfigError('Run switches must be True or False')
    cfg = validate_config(CONFIG)
    args = SimpleNamespace(live=False, all=False, mint=None, file=Path(REPLAY_FILE) if REPLAY_FILE else None)
    validate_setup(cfg, args, kind)
    return cfg, args


if __name__ == '__main__':
    run(main)
