"""ZeroSlip live_sniper_bot.py: edit settings below, then run python3 live_sniper_bot.py.

Python 3.11+. Install the packages listed below once in your Python environment.
Alternatively, uv run live_sniper_bot.py handles them automatically. No config files or flags.
Generated by tools/build_standalone.py from scripts/; edit strategy logic there.
"""
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "aiohttp>=3.12,<4",
#   "websockets>=15,<16",
#   "cachetools>=5.5,<8",
#   "orjson>=3.10,<4",
#   "zstandard>=0.23,<1",
# ]
# ///

# SETTINGS — edit this section. Nothing below sends orders unless LIVE is True.
LIVE = False  # Paper trades / read-only previews. Backtesting never submits orders.
API_KEY = ''  # Live only: your wallet API key. Keep this file private if filled.
PRIVATE_KEY = ''  # Or a base58 private key; API_KEY takes precedence.
CONFIG = {
    'sniper': {
        'token_mint': '',  # Paste a mint; empty means qualifying new launches.
        'min_initial_buy': 20.0,  # SOL-equivalent launch threshold.
        'take_profit': 50.0,  # Percent.
        'stop_loss': 20.0,  # Percent.
        'idle_seconds': 300.0,
    },
    'trade': {
        'buy_amount': 0.001,  # SOL-equivalent.
        'buy_slippage': 20.0,
        'sell_slippage': 99.0,
        'priority_fee': 0.0001,
    },
}

# IMPLEMENTATION — the same runtime and strategy as scripts/, bundled into this file.
from types import SimpleNamespace
import asyncio
import copy
import logging
import math
from pathlib import Path
from urllib.parse import urlparse
import aiohttp
import orjson
from cachetools import TTLCache
import websockets
import time


BASE58_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'


WSOL = 'So11111111111111111111111111111111111111112'


USDC = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'


SOL_USDC_POOL = 'Gf7sXMoP8iRw4iiXmJ1nq4vxcRycbGXy5RL8a8LnTd3v'


DEFAULTS = {
    'network': {
        'trade_url': 'https://api.zeroslip.ai',
        'stream_url': 'wss://stream.zeroslip.ai/',
        'replay_url': 'https://replay.pumpapi.io',
        'rpc_url': 'https://api.mainnet-beta.solana.com',
    },
    'trade': {
        'buy_amount': 0.001,
        'buy_slippage': 20.0,
        'sell_slippage': 99.0,
        'priority_fee': 0.0001,
        'confirmation_seconds': 3.0,
    },
    'wallet': {'public_key': ''},
    'copytrader': {'wallets': [], 'token_mints': [], 'buy_fraction': 0.1, 'max_buy_amount': 0.01},
    'sniper': {
        'token_mint': '',
        'min_initial_buy': 20.0,
        'take_profit': 50.0,
        'stop_loss': 20.0,
        'idle_seconds': 300.0,
    },
    'backtest': {
        'hours': 10,
        'allow_gaps': False,
        'buy_latency_ms': 400,
        'sell_latency_ms': 400,
        'service_fee': 0.0025,
        'extra_fee': 0.0005,
    },
    'sell': {'token_mints': [], 'slippage': 100.0},
}


class ConfigError(ValueError):
    pass


class StopBot(RuntimeError):
    """Execution is rejected or uncertain: stop without sending another order."""


def address(value, label):
    if not isinstance(value, str) or not 32 <= len(value) <= 44 or any(c not in BASE58_ALPHABET for c in value):
        raise ConfigError(f'{label} must be a Solana base58 address')
    # Verify decoded length, not just the alphabet.
    number = 0
    for char in value:
        number = number * 58 + BASE58_ALPHABET.index(char)
    size = (number.bit_length() + 7) // 8 + len(value) - len(value.lstrip('1'))
    if size != 32:
        raise ConfigError(f'{label} must decode to 32 bytes')
    return value


def validate_config(overrides):
    """Merge and validate settings from either TOML or a single-file Python dict."""
    cfg = copy.deepcopy(DEFAULTS)
    if not isinstance(overrides, dict):
        raise ConfigError('Settings must be a dictionary of configuration sections')
    for section, values in overrides.items():
        if section not in cfg or not isinstance(values, dict):
            raise ConfigError(f'Unknown or invalid configuration section: {section}')
        for key, value in values.items():
            if section == 'trade' and key == 'quote_mint':
                logging.getLogger(__name__).warning(
                    'Ignoring deprecated trade.quote_mint; SOL/USDC quotes come from each event. '
                    'Remove this key from your config'
                )
                continue
            if key not in cfg[section]:
                raise ConfigError(f'Unknown configuration option: {section}.{key}')
            default = cfg[section][key]
            if isinstance(default, bool):
                valid = isinstance(value, bool)
            elif isinstance(default, (float, int)):
                valid = isinstance(value, (float, int)) and not isinstance(value, bool) and math.isfinite(value)
            else:
                valid = isinstance(value, type(default))
            if not valid:
                raise ConfigError(f'Invalid value type: {section}.{key}')
            cfg[section][key] = value
    for section, key in [
        ('trade', 'buy_amount'),
        ('trade', 'confirmation_seconds'),
        ('copytrader', 'max_buy_amount'),
        ('sniper', 'idle_seconds'),
        ('sniper', 'take_profit'),
        ('sniper', 'stop_loss'),
    ]:
        if cfg[section][key] <= 0:
            raise ConfigError(f'{section}.{key} must be positive')
    for section, key in [('backtest', 'hours')]:
        if not isinstance(cfg[section][key], int) or cfg[section][key] < 1:
            raise ConfigError(f'{section}.{key} must be a positive integer')
    for key in ('buy_slippage', 'sell_slippage'):
        if not 0 <= cfg['trade'][key] < 100:
            raise ConfigError(f'trade.{key} must be between 0 and 100 (exclusive)')
    if not 0 <= cfg['sell']['slippage'] <= 100:
        raise ConfigError('sell.slippage must be between 0 and 100 (inclusive)')
    if not 0 < cfg['copytrader']['buy_fraction'] <= 1:
        raise ConfigError('copytrader.buy_fraction must be between 0 and 1')
    if not 0 < cfg['sniper']['stop_loss'] < 100:
        raise ConfigError('sniper.stop_loss must be between 0 and 100 (exclusive)')
    for section, key in [
        ('trade', 'priority_fee'),
        ('sniper', 'min_initial_buy'),
        ('backtest', 'buy_latency_ms'),
        ('backtest', 'sell_latency_ms'),
        ('backtest', 'service_fee'),
        ('backtest', 'extra_fee'),
    ]:
        if cfg[section][key] < 0:
            raise ConfigError(f'{section}.{key} cannot be negative')
    if cfg['backtest']['service_fee'] + cfg['backtest']['extra_fee'] >= 1:
        raise ConfigError('Backtest fee fractions must total less than 1')
    for key, url in cfg['network'].items():
        parsed = urlparse(url)
        if (
            parsed.scheme != ('wss' if key == 'stream_url' else 'https')
            or not parsed.hostname
            or parsed.username
            or parsed.password
            or parsed.query
        ):
            raise ConfigError(f'network.{key} must be a secure URL without credentials or query parameters')
    for section, key in [('copytrader', 'wallets'), ('copytrader', 'token_mints'), ('sell', 'token_mints')]:
        for item in cfg[section][key]:
            address(item, f'{section}.{key}')
    if cfg['sniper']['token_mint']:
        address(cfg['sniper']['token_mint'], 'sniper.token_mint')
    return cfg


def validate_setup(cfg, args, kind):
    if cfg['wallet']['public_key']:
        address(cfg['wallet']['public_key'], 'wallet.public_key')
    if kind == 'copytrader' and not cfg['copytrader']['wallets']:
        raise ConfigError('Set copytrader.wallets to the public wallets you want to follow')
    if kind == 'copytrader' and cfg['wallet']['public_key'] in cfg['copytrader']['wallets']:
        raise ConfigError('Do not copy your own trading wallet')
    if kind == 'sell':
        if not args.live and not cfg['wallet']['public_key']:
            raise ConfigError('Sell preview needs wallet.public_key (or --wallet in CLI scripts)')
        if args.all and (args.mint or cfg['sell']['token_mints']):
            raise ConfigError('Choose all balances or specific token mints, not both')
        if not args.all and not cfg['sell']['token_mints']:
            raise ConfigError('Set sell.token_mints or select all balances')
    if getattr(args, 'live', False):
        credentials()


def trusted_pool(event):
    return not event.get('mayhemMode') and (
        event.get('pool') == 'pump' or (event.get('pool') == 'pump-amm' and event.get('poolCreatedBy') == 'pump')
    )


def positive(value):
    try:
        value = float(value)
        return value if math.isfinite(value) and value > 0 else 0.0
    except (ValueError, TypeError):
        return 0.0


class QuoteSizing:
    """Original two-quote strategy: SOL sizes, converted to USDC at stream price."""

    def __init__(self):
        self.sol_price = 80.0  # Original fallback until the trusted pool updates.

    def observe(self, event):
        if event.get('poolId') != SOL_USDC_POOL:
            return False
        price = positive(event.get('price'))
        if price:
            self.sol_price = 1 / price
        return True

    def amount(self, quote, sol_amount):
        return sol_amount if quote == WSOL else sol_amount * self.sol_price

    @staticmethod
    def supports(quote):
        return quote in (WSOL, USDC)


async def api_post(session, url, payload, *, rpc=False):
    # Never log the credential-bearing payload or a server body that may echo it.
    try:
        async with session.post(url, json=payload, allow_redirects=False) as response:
            if response.status != 200:
                if rpc:
                    raise StopBot(f'RPC returned HTTP {response.status}; retry the balance preview')
                raise StopBot(f'API returned HTTP {response.status}; check the order outcome before retrying')
            data = await response.json()
        if not isinstance(data, dict) or data.get('err') or data.get('error'):
            if rpc:
                error = data.get('error') if isinstance(data, dict) else 'Invalid response'
                raise StopBot(f'RPC balance query failed: {error}')
            raise StopBot('API rejected the request; check the order outcome before retrying')
        return data
    except (aiohttp.ClientError, asyncio.TimeoutError, ValueError) as exc:
        if rpc:
            raise StopBot(f'RPC balance query unavailable: {type(exc).__name__}: {exc}') from exc
        raise StopBot('API response unavailable; order outcome is uncertain. Check the wallet before retrying') from exc


class Trader:
    def __init__(self, cfg, session, live=False):
        self.cfg, self.session, self.live = cfg, session, live
        self.events = TTLCache(maxsize=10000, ttl=300)
        self.paper_positions = {}
        self.paper_totals = {WSOL: 0.0, USDC: 0.0}
        self.paper_pnl_sol = 0.0
        self.paper_missed = self.paper_buys = self.paper_sells = 0
        self.quotes = QuoteSizing()

    def observe(self, event):
        self.quotes.observe(event)
        signature = event.get('signature')
        if signature:
            self.events.setdefault(signature, []).append(event)

    async def order(self, action, mint, quote, amount, price, tokens=0):
        if not self.live:
            logging.info('PAPER %s mint=%s amount=%s quote=%s', action.upper(), mint, amount, quote)
            if action == 'buy':
                quantity = float(amount) / price
                self.paper_positions[mint] = {
                    'tokens': quantity,
                    'cost': float(amount),
                    'sol_price': self.quotes.sol_price,
                }
                self.paper_buys += 1
            else:
                quantity = (
                    tokens * float(amount[:-1]) / 100
                    if isinstance(amount, str) and amount.endswith('%')
                    else float(amount)
                )
                quantity = min(tokens, quantity)
                position = self.paper_positions[mint]
                cost = position['cost'] * quantity / position['tokens']
                pnl = quantity * price - cost
                self.paper_totals[quote] += pnl
                self.paper_pnl_sol += pnl if quote == WSOL else pnl / position['sol_price']
                self.paper_sells += 1
                logging.info(
                    'PAPER RESULT mint=%s move=%+.2f%% pnl=%+.8f quote=%s total_sol=%+.8f',
                    mint,
                    (quantity * price / cost - 1) * 100,
                    pnl,
                    quote,
                    self.paper_pnl_sol,
                )
                position['tokens'] -= quantity
                position['cost'] -= cost
                if position['tokens'] <= 0:
                    self.paper_positions.pop(mint)
            return {'price': price, 'tokenAmount': quantity, 'quoteAmount': quantity * price}
        settings = self.cfg['trade']
        payload = {
            **credentials(),
            'action': action,
            'mint': mint,
            'quoteMint': quote,
            'amount': amount,
            'denominatedInQuote': 'true' if action == 'buy' else 'false',
            'slippage': settings['buy_slippage' if action == 'buy' else 'sell_slippage'],
            'priorityFee': settings['priority_fee'],
        }
        response = await api_post(self.session, self.cfg['network']['trade_url'], payload)
        signature = response.get('signature')
        if not isinstance(signature, str) or not signature:
            raise StopBot('API did not return a signature. Check the wallet before retrying')
        logging.info('Submitted %s mint=%s signature=%s', action, mint, signature)
        deadline = asyncio.get_running_loop().time() + settings['confirmation_seconds']
        while asyncio.get_running_loop().time() < deadline:
            for event in self.events.get(signature, []):
                if (
                    event.get('action') == action
                    and event.get('mint') == mint
                    and positive(event.get('price'))
                    and positive(event.get('tokenAmount'))
                ):
                    logging.info('Confirmed %s mint=%s signature=%s', action, mint, signature)
                    return event
            await asyncio.sleep(0.1)
        raise StopBot(
            f'No trade event observed for {signature}. Check the wallet before restarting; no order was retried'
        )

    def report(self):
        if not self.live:
            logging.info(
                'Paper summary: buys=%s sells=%s missed=%s open=%s '
                'realized_pnl=%+.8f SOL-equivalent; WSOL=%+.8f USDC=%+.8f (fees excluded)',
                self.paper_buys,
                self.paper_sells,
                self.paper_missed,
                len(self.paper_positions),
                self.paper_pnl_sol,
                self.paper_totals[WSOL],
                self.paper_totals[USDC],
            )


async def run_stream(cfg, trader, on_event, on_tick, accept_event=None):
    # Independent token workers restore the original cross-token concurrency.
    # A token's exits stay in stream order so proportional bookkeeping is stable.
    queues = {}
    workers = set()
    failure = asyncio.get_running_loop().create_future()

    def completed(task):
        workers.discard(task)
        if not task.cancelled() and task.exception() is not None and not failure.done():
            failure.set_exception(task.exception())

    async def token_worker(mint, queue):
        while True:
            try:
                event = await asyncio.wait_for(queue.get(), timeout=1)
                await on_event(event)
            except asyncio.TimeoutError:
                pass
            tracking = await on_tick(mint)
            if not tracking and queue.empty():
                # No await between checking/removing: reader cannot enqueue into
                # an orphaned queue. Untracked tokens don't retain idle workers.
                queues.pop(mint, None)
                return

    async def reader():
        delay = 0.4
        while True:
            connected_at = None
            try:
                async with websockets.connect(cfg['network']['stream_url'], max_size=8 << 20) as socket:
                    connected_at = asyncio.get_running_loop().time()
                    logging.info('Connected to market stream (%s)', 'LIVE' if trader.live else 'PAPER')
                    async for message in socket:
                        try:
                            event = orjson.loads(message)
                        except (ValueError, TypeError):
                            continue
                        if not isinstance(event, dict):
                            continue
                        trader.observe(event)
                        mint = event.get('mint') or '__market__'
                        # Once a token worker exists, retain its market updates
                        # even while its buy hasn't registered a position yet.
                        if accept_event is not None and not accept_event(event) and mint not in queues:
                            continue
                        if mint not in queues:
                            queues[mint] = asyncio.Queue(maxsize=10000)
                            task = asyncio.create_task(token_worker(mint, queues[mint]))
                            workers.add(task)
                            task.add_done_callback(completed)
                        try:
                            queues[mint].put_nowait(event)
                        except asyncio.QueueFull as exc:
                            raise StopBot('Token event queue overflowed; reconcile wallet positions') from exc
                    reason = f'close={socket.close_code} {socket.close_reason}'
            except (OSError, websockets.exceptions.WebSocketException) as exc:
                reason = f'{type(exc).__name__}: {exc}'
            if connected_at is not None and asyncio.get_running_loop().time() - connected_at >= 30:
                delay = 0.4
            logging.warning('Stream disconnected (%s); reconnecting in %.1f seconds', reason, delay)
            await asyncio.sleep(delay)
            delay = min(delay * 2, 30)

    stream = asyncio.create_task(reader())
    try:
        done, _ = await asyncio.wait([stream, failure], return_when=asyncio.FIRST_COMPLETED)
        for task in done:
            task.result()
    finally:
        stream.cancel()
        for task in workers:
            task.cancel()
        await asyncio.gather(stream, *workers, return_exceptions=True)
        if not failure.done():
            failure.cancel()
        trader.report()


def run(main):
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logging.info('Stopped. Existing live positions remain in the wallet.')
    except (StopBot, ConfigError) as exc:
        logging.error('%s', exc)
        raise SystemExit(1) from exc
    except Exception as exc:
        logging.exception('Unexpected runtime failure (%s); stopped', type(exc).__name__)
        raise SystemExit(1) from exc


class Sniper:
    def __init__(self, cfg, trader, clock=time.monotonic):
        self.cfg, self.trader, self.clock = cfg, trader, clock
        self.positions = {}
        self.pending = {}
        self.finished = set()
        self.quotes = QuoteSizing()

    async def on_event(self, event):
        mint, quote = event.get('mint'), event.get('quoteMint')
        price = positive(event.get('price'))
        if not mint:
            return
        selected = self.cfg['sniper']['token_mint']
        if selected:
            # Direct-token mode works across supported venues. Restrict to real
            # trade events and buy once at the first observed market price.
            eligible = mint == selected and event.get('action') in ('buy', 'sell')
        else:
            eligible = (
                event.get('action') == 'create'
                and event.get('pool') == 'pump'
                and trusted_pool(event)
                and (
                    positive(event.get('quoteAmount'))
                    > self.quotes.amount(quote, self.cfg['sniper']['min_initial_buy'])
                )
            )
        if mint in self.pending:
            pending = self.pending[mint]
            if (
                event.get('action') not in ('buy', 'sell')
                or not price
                or not self.quotes.supports(quote)
                or (not selected and not trusted_pool(event))
            ):
                return
            if quote != pending['quote']:
                price = price / self.quotes.sol_price if quote != WSOL else price * self.quotes.sol_price
            self.pending.pop(mint)
            ceiling = pending['decision'] / (1 - self.cfg['trade']['buy_slippage'] / 100)
            if price > ceiling:
                self.trader.paper_missed += 1
                logging.info(
                    'PAPER MISS mint=%s price=%s ceiling=%s missed=%s', mint, price, ceiling, self.trader.paper_missed
                )
                if selected:
                    self.finished.add(mint)
                return
            await self.buy(mint, pending['quote'], price)
            return  # The fill event cannot also trigger a take-profit.
        if mint not in self.positions:
            if not self.quotes.supports(quote) or not price:
                return
            if not eligible or mint in self.finished:
                return
            if not self.trader.live:
                self.pending[mint] = {'decision': price, 'quote': quote, 'last': self.clock()}
                logging.info('PAPER PENDING BUY mint=%s; waiting for the next trade price', mint)
            else:
                await self.buy(mint, quote, price)
            return
        # As upstream, any token event resets idle; only these actions drive TP/SL.
        self.positions[mint]['last'] = self.clock()
        if event.get('action') not in ('buy', 'sell', 'add', 'remove'):
            return
        if not price or not self.quotes.supports(quote):
            return
        if not selected and not trusted_pool(event):
            return
        position = self.positions[mint]
        # Compare prices in the position's entry quote, even across SOL/USDC pools.
        if quote != position['quote']:
            price = price / self.quotes.sol_price if quote != WSOL else price * self.quotes.sol_price
        position.update(price=price, last=self.clock())
        change = (price - position['entry']) / position['entry'] * 100
        if change > self.cfg['sniper']['take_profit'] or change < -self.cfg['sniper']['stop_loss']:
            await self.exit(mint, 'take profit' if change > self.cfg['sniper']['take_profit'] else 'stop loss')

    async def buy(self, mint, quote, price):
        result = await self.trader.order(
            'buy',
            mint,
            quote,
            self.quotes.amount(quote, self.cfg['trade']['buy_amount']),
            price,
        )
        self.positions[mint] = {
            'entry': positive(result['price']),
            'price': positive(result['price']),
            'tokens': positive(result['tokenAmount']),
            'last': self.clock(),
            'quote': quote,
        }
        logging.info(
            'Opened %s; TP=%s%% SL=%s%%', mint, self.cfg['sniper']['take_profit'], self.cfg['sniper']['stop_loss']
        )

    def accept_event(self, event):
        if self.quotes.observe(event):
            return False
        mint = event.get('mint')
        return bool(mint) and (
            mint in self.positions
            or mint in self.pending
            or mint == self.cfg['sniper']['token_mint']
            or (event.get('action') == 'create' and event.get('pool') == 'pump' and trusted_pool(event))
        )

    async def exit(self, mint, reason):
        position = self.positions[mint]
        await self.trader.order('sell', mint, position['quote'], '100%', position['price'], position['tokens'])
        self.positions.pop(mint)
        if self.cfg['sniper']['token_mint']:
            self.finished.add(mint)
        logging.info('Closed %s (%s)', mint, reason)

    async def on_tick(self, mint=None):
        for token, pending in list(self.pending.items()):
            if (mint is None or mint == token) and self.clock() - pending['last'] > self.cfg['sniper']['idle_seconds']:
                self.pending.pop(token)
                self.trader.paper_missed += 1
                if self.cfg['sniper']['token_mint']:
                    self.finished.add(token)
                logging.info('PAPER MISS mint=%s; no subsequent trade before idle timeout', token)
        positions = (
            list(self.positions.items())
            if mint is None
            else ([(mint, self.positions[mint])] if mint in self.positions else [])
        )
        for token, position in positions:
            if self.clock() - position['last'] > self.cfg['sniper']['idle_seconds']:
                await self.exit(token, 'idle timeout')
        return mint in self.positions or mint in self.pending


async def main():
    cfg, args = setup('sniper')
    async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=30)) as session:
        trader = Trader(cfg, session, args.live)
        strategy = Sniper(cfg, trader)
        await run_stream(cfg, trader, strategy.on_event, strategy.on_tick, strategy.accept_event)


def credentials():
    api_key = API_KEY.strip()
    private_key = PRIVATE_KEY.strip()
    if not api_key and not private_key:
        raise ConfigError('LIVE = True needs API_KEY or PRIVATE_KEY in the settings at the top')
    return {'apiKey': api_key} if api_key else {'privateKey': private_key}


def setup(kind):
    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
    if not isinstance(LIVE, bool) or not isinstance(False, bool):
        raise ConfigError('Run switches must be True or False')
    cfg = validate_config(CONFIG)
    args = SimpleNamespace(live=LIVE, all=False, mint=None, file=Path('') if '' else None)
    validate_setup(cfg, args, kind)
    return cfg, args


if __name__ == '__main__':
    run(main)
