"""ZeroSlip sell_all_tokens.py: edit settings below, then run python3 sell_all_tokens.py.

Python 3.11+. Install the packages listed below once in your Python environment.
Alternatively, uv run sell_all_tokens.py handles them automatically. No config files or flags.
Generated by tools/build_standalone.py from scripts/; edit strategy logic there.
"""
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "aiohttp>=3.12,<4",
#   "websockets>=15,<16",
#   "cachetools>=5.5,<8",
#   "orjson>=3.10,<4",
#   "zstandard>=0.23,<1",
# ]
# ///

# SETTINGS — edit this section. Nothing below sends orders unless LIVE is True.
LIVE = False  # Paper trades / read-only previews. Backtesting never submits orders.
API_KEY = ''  # Live only: your wallet API key. Keep this file private if filled.
PRIVATE_KEY = ''  # Or a base58 private key; API_KEY takes precedence.
SELL_ALL = True  # False: sell only the token_mints listed below.
CONFIG = {
    'wallet': {'public_key': ''},  # Public wallet to preview; live sells use the credential wallet.
    'sell': {'token_mints': [], 'slippage': 100.0},  # 100 accepts any price; review before live use.
    'trade': {'priority_fee': 0.0001},
}

# IMPLEMENTATION — the same runtime and strategy as scripts/, bundled into this file.
from types import SimpleNamespace
import asyncio
import copy
import logging
import math
from pathlib import Path
from urllib.parse import urlparse
import aiohttp


BASE58_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'


WSOL = 'So11111111111111111111111111111111111111112'


USDC = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'


DEFAULTS = {
    'network': {
        'trade_url': 'https://api.zeroslip.ai',
        'stream_url': 'wss://stream.zeroslip.ai/',
        'replay_url': 'https://replay.pumpapi.io',
        'rpc_url': 'https://api.mainnet-beta.solana.com',
    },
    'trade': {
        'buy_amount': 0.001,
        'buy_slippage': 20.0,
        'sell_slippage': 99.0,
        'priority_fee': 0.0001,
        'confirmation_seconds': 3.0,
    },
    'wallet': {'public_key': ''},
    'copytrader': {'wallets': [], 'token_mints': [], 'buy_fraction': 0.1, 'max_buy_amount': 0.01},
    'sniper': {
        'token_mint': '',
        'min_initial_buy': 20.0,
        'take_profit': 50.0,
        'stop_loss': 20.0,
        'idle_seconds': 300.0,
    },
    'backtest': {
        'hours': 10,
        'allow_gaps': False,
        'buy_latency_ms': 400,
        'sell_latency_ms': 400,
        'service_fee': 0.0025,
        'extra_fee': 0.0005,
    },
    'sell': {'token_mints': [], 'slippage': 100.0},
}


class ConfigError(ValueError):
    pass


class StopBot(RuntimeError):
    """Execution is rejected or uncertain: stop without sending another order."""


def address(value, label):
    if not isinstance(value, str) or not 32 <= len(value) <= 44 or any(c not in BASE58_ALPHABET for c in value):
        raise ConfigError(f'{label} must be a Solana base58 address')
    # Verify decoded length, not just the alphabet.
    number = 0
    for char in value:
        number = number * 58 + BASE58_ALPHABET.index(char)
    size = (number.bit_length() + 7) // 8 + len(value) - len(value.lstrip('1'))
    if size != 32:
        raise ConfigError(f'{label} must decode to 32 bytes')
    return value


def validate_config(overrides):
    """Merge and validate settings from either TOML or a single-file Python dict."""
    cfg = copy.deepcopy(DEFAULTS)
    if not isinstance(overrides, dict):
        raise ConfigError('Settings must be a dictionary of configuration sections')
    for section, values in overrides.items():
        if section not in cfg or not isinstance(values, dict):
            raise ConfigError(f'Unknown or invalid configuration section: {section}')
        for key, value in values.items():
            if section == 'trade' and key == 'quote_mint':
                logging.getLogger(__name__).warning(
                    'Ignoring deprecated trade.quote_mint; SOL/USDC quotes come from each event. '
                    'Remove this key from your config'
                )
                continue
            if key not in cfg[section]:
                raise ConfigError(f'Unknown configuration option: {section}.{key}')
            default = cfg[section][key]
            if isinstance(default, bool):
                valid = isinstance(value, bool)
            elif isinstance(default, (float, int)):
                valid = isinstance(value, (float, int)) and not isinstance(value, bool) and math.isfinite(value)
            else:
                valid = isinstance(value, type(default))
            if not valid:
                raise ConfigError(f'Invalid value type: {section}.{key}')
            cfg[section][key] = value
    for section, key in [
        ('trade', 'buy_amount'),
        ('trade', 'confirmation_seconds'),
        ('copytrader', 'max_buy_amount'),
        ('sniper', 'idle_seconds'),
        ('sniper', 'take_profit'),
        ('sniper', 'stop_loss'),
    ]:
        if cfg[section][key] <= 0:
            raise ConfigError(f'{section}.{key} must be positive')
    for section, key in [('backtest', 'hours')]:
        if not isinstance(cfg[section][key], int) or cfg[section][key] < 1:
            raise ConfigError(f'{section}.{key} must be a positive integer')
    for key in ('buy_slippage', 'sell_slippage'):
        if not 0 <= cfg['trade'][key] < 100:
            raise ConfigError(f'trade.{key} must be between 0 and 100 (exclusive)')
    if not 0 <= cfg['sell']['slippage'] <= 100:
        raise ConfigError('sell.slippage must be between 0 and 100 (inclusive)')
    if not 0 < cfg['copytrader']['buy_fraction'] <= 1:
        raise ConfigError('copytrader.buy_fraction must be between 0 and 1')
    if not 0 < cfg['sniper']['stop_loss'] < 100:
        raise ConfigError('sniper.stop_loss must be between 0 and 100 (exclusive)')
    for section, key in [
        ('trade', 'priority_fee'),
        ('sniper', 'min_initial_buy'),
        ('backtest', 'buy_latency_ms'),
        ('backtest', 'sell_latency_ms'),
        ('backtest', 'service_fee'),
        ('backtest', 'extra_fee'),
    ]:
        if cfg[section][key] < 0:
            raise ConfigError(f'{section}.{key} cannot be negative')
    if cfg['backtest']['service_fee'] + cfg['backtest']['extra_fee'] >= 1:
        raise ConfigError('Backtest fee fractions must total less than 1')
    for key, url in cfg['network'].items():
        parsed = urlparse(url)
        if (
            parsed.scheme != ('wss' if key == 'stream_url' else 'https')
            or not parsed.hostname
            or parsed.username
            or parsed.password
            or parsed.query
        ):
            raise ConfigError(f'network.{key} must be a secure URL without credentials or query parameters')
    for section, key in [('copytrader', 'wallets'), ('copytrader', 'token_mints'), ('sell', 'token_mints')]:
        for item in cfg[section][key]:
            address(item, f'{section}.{key}')
    if cfg['sniper']['token_mint']:
        address(cfg['sniper']['token_mint'], 'sniper.token_mint')
    return cfg


def validate_setup(cfg, args, kind):
    if cfg['wallet']['public_key']:
        address(cfg['wallet']['public_key'], 'wallet.public_key')
    if kind == 'copytrader' and not cfg['copytrader']['wallets']:
        raise ConfigError('Set copytrader.wallets to the public wallets you want to follow')
    if kind == 'copytrader' and cfg['wallet']['public_key'] in cfg['copytrader']['wallets']:
        raise ConfigError('Do not copy your own trading wallet')
    if kind == 'sell':
        if not args.live and not cfg['wallet']['public_key']:
            raise ConfigError('Sell preview needs wallet.public_key (or --wallet in CLI scripts)')
        if args.all and (args.mint or cfg['sell']['token_mints']):
            raise ConfigError('Choose all balances or specific token mints, not both')
        if not args.all and not cfg['sell']['token_mints']:
            raise ConfigError('Set sell.token_mints or select all balances')
    if getattr(args, 'live', False):
        credentials()


def positive(value):
    try:
        value = float(value)
        return value if math.isfinite(value) and value > 0 else 0.0
    except (ValueError, TypeError):
        return 0.0


async def api_post(session, url, payload, *, rpc=False):
    # Never log the credential-bearing payload or a server body that may echo it.
    try:
        async with session.post(url, json=payload, allow_redirects=False) as response:
            if response.status != 200:
                if rpc:
                    raise StopBot(f'RPC returned HTTP {response.status}; retry the balance preview')
                raise StopBot(f'API returned HTTP {response.status}; check the order outcome before retrying')
            data = await response.json()
        if not isinstance(data, dict) or data.get('err') or data.get('error'):
            if rpc:
                error = data.get('error') if isinstance(data, dict) else 'Invalid response'
                raise StopBot(f'RPC balance query failed: {error}')
            raise StopBot('API rejected the request; check the order outcome before retrying')
        return data
    except (aiohttp.ClientError, asyncio.TimeoutError, ValueError) as exc:
        if rpc:
            raise StopBot(f'RPC balance query unavailable: {type(exc).__name__}: {exc}') from exc
        raise StopBot('API response unavailable; order outcome is uncertain. Check the wallet before retrying') from exc


def run(main):
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logging.info('Stopped. Existing live positions remain in the wallet.')
    except (StopBot, ConfigError) as exc:
        logging.error('%s', exc)
        raise SystemExit(1) from exc
    except Exception as exc:
        logging.exception('Unexpected runtime failure (%s); stopped', type(exc).__name__)
        raise SystemExit(1) from exc


TOKEN_PROGRAMS = (
    'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
)


async def balances(cfg, session, live):
    if live:
        # Defaults to the credential's wallet; never scan one wallet then sell
        # from a different one. This documented read incurs an API balance fee.
        data = await api_post(session, cfg['network']['trade_url'], {**credentials(), 'action': 'getBalances'})
        result = data.get('tokenBalances')
        if not isinstance(result, dict):
            raise StopBot('API did not return token balances')
        return result
    result = {}
    for program in TOKEN_PROGRAMS:
        payload = {
            'jsonrpc': '2.0',
            'id': 1,
            'method': 'getTokenAccountsByOwner',
            'params': [
                cfg['wallet']['public_key'],
                {'programId': program},
                {'encoding': 'jsonParsed', 'commitment': 'confirmed'},
            ],
        }
        data = await api_post(session, cfg['network']['rpc_url'], payload, rpc=True)
        accounts = data.get('result', {}).get('value')
        if not isinstance(accounts, list):
            raise StopBot('RPC did not return token accounts')
        for account in accounts:
            info = account['account']['data']['parsed']['info']
            amount = info['tokenAmount']
            quantity = positive(amount.get('uiAmountString'))
            mint = info['mint']
            entry = result.setdefault(mint, {'balance': 0, 'frozen': False})
            entry['balance'] += quantity
            entry['frozen'] = entry['frozen'] or info.get('state') == 'frozen'
    return result


def select_balances(cfg, holdings, all_tokens):
    wanted = cfg['sell']['token_mints']
    # Preserve both trading quote assets, including explicit mint selections.
    excluded = {WSOL, USDC}
    return {
        mint: info
        for mint, info in holdings.items()
        if mint not in excluded and (all_tokens or mint in wanted) and positive(info.get('balance'))
    }


async def sell_selected(cfg, session, live, all_tokens):
    selected = select_balances(cfg, await balances(cfg, session, live), all_tokens)
    if not selected:
        logging.info('No matching token balances to sell.')
        return
    for mint, info in selected.items():
        if info.get('frozen'):
            logging.warning('Skipping frozen balance mint=%s; no burn is attempted', mint)
            continue
        logging.info('%s SELL 100%% mint=%s balance=%s', 'LIVE' if live else 'PREVIEW', mint, info['balance'])
        if not live:
            continue
        data = await api_post(
            session,
            cfg['network']['trade_url'],
            {
                **credentials(),
                'action': 'sell',
                'mint': mint,
                'amount': '100%',
                'denominatedInQuote': 'false',
                'slippage': cfg['sell']['slippage'],
                'priorityFee': cfg['trade']['priority_fee'],
                'guaranteedDelivery': 'true',
            },
        )
        if data.get('confirmed') is not True or not data.get('signature'):
            raise StopBot('Sale not confirmed; check the wallet before retrying. No burn was attempted')
        quote = next(
            (trade.get('quoteMint') for trade in data.get('trades', []) if isinstance(trade, dict)), 'auto-selected'
        )
        logging.info('Sale confirmed mint=%s quote=%s signature=%s', mint, quote, data['signature'])


async def main():
    cfg, args = setup('sell')
    async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=30)) as session:
        await sell_selected(cfg, session, args.live, args.all)


def credentials():
    api_key = API_KEY.strip()
    private_key = PRIVATE_KEY.strip()
    if not api_key and not private_key:
        raise ConfigError('LIVE = True needs API_KEY or PRIVATE_KEY in the settings at the top')
    return {'apiKey': api_key} if api_key else {'privateKey': private_key}


def setup(kind):
    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
    if not isinstance(LIVE, bool) or not isinstance(SELL_ALL, bool):
        raise ConfigError('Run switches must be True or False')
    cfg = validate_config(CONFIG)
    args = SimpleNamespace(live=LIVE, all=SELL_ALL, mint=None, file=Path('') if '' else None)
    validate_setup(cfg, args, kind)
    return cfg, args


if __name__ == '__main__':
    run(main)
